### ISSUE TITLE
chatgpt windows

### ISSUE THREAD

**Issue by drxionger** [bulutthecat/TalkGPT#1]

**Comment by bulutthecat** [comment]
could you provide an error?

**Comment by cmdgames** [comment]
or a description?

**Comment by bulutthecat** [comment]
blank, no response.

**Comment by bulutthecat** [comment]
I closed the error as “not fixing/cannot reproduce” Sent from Mail for Windows From: cmdgamesSent: Saturday, February 4, 2023 11:54 AMTo: bulutthecat/TalkGPTCc: bulutthecat; CommentSubject: Re: [bulutthecat/TalkGPT] chatgpt windows (Issue #1) or a description?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
